# version: '3.9'

# services:
#   db:
#     image: postgres:17
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: electro_tsn_development
#     volumes:
#       - db-data:/var/lib/postgresql/data
#       - ./db/init:/docker-entrypoint-initdb.d
#     ports:
#       - "5432:5432"

#   redis:
#     container_name: electrotsn-redis
#     image: redis:7
#     ports:
#       - "6379:6379"

#   app:
#     build: .
#     command: sh -c "until nc -z db 5432; do echo 'Waiting for PostgreSQL...'; sleep 1; done && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

#     environment:
#       RAILS_ENV: development
#       RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
#     volumes:
#       - .:/app
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - redis

#   sidekiq:
#     build: .
#     command: sh -c "until nc -z db 5432; do echo 'Waiting for PostgreSQL...'; sleep 1; done && bundle exec sidekiq"

#     environment:
#       RAILS_ENV: development
#       RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
#       REDIS_URL: redis://redis:6379/0
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#       - redis
#     restart: on-failure

# volumes:
#   db-data:
